### ISSUE TITLE
Investigate React UI Libraries

### ISSUE THREAD

**Issue by jeremy-jtlo** [gdirk07/PokemonChecker#37]
Though Semantic React has been mentioned before, it has been a few years since I'd actively used it. There are plenty of alternatives out, so this issue exists to point out the work of choosing on a new framework.

https://os-system.com/blog/best-react-ui-libraries-10-most-popular-libraries/

https://www.codeinwp.com/blog/react-ui-component-libraries-frameworks/

It seems that "react bootstrap", "material UI", and "chakra" are contenders, though Semantic continues to appear on the lists.

**Comment by gdirk07** [comment]
So I took a look at a few. I also used https://retool.com/blog/react-component-libraries/

Semantic is purposed for web sites more so than applications which could end up annoying if we want to build a hybrid mobile/web app.

Material UI (MUI) has the most Stack Overflow posts and is one of the more popular ones.

react boostrap was made before react itself and seems to be lighter (less features) than MUI and ANTD, also like Semantic UI, its built towards websites rather than applications.

Chakra is new and upcoming, not a lot of Stack Overflow activity.

I'm not going to make a final decision and I'd like your input @jeremy-jtlo , I think Material UI would be interesting to try out as its one of the more popular one with huge community support.

**Comment by jeremy-jtlo** [comment]
From what I remember in that react native investigation I did earlier this year, any of the above you mentioned still work. The reasoning for this is that these component libraries ship JSX components, which will render just fine in React for web or React Native - the question is just what look we prefer or the level of support we're looking for when we run into an issue.

For example, Bootstrap is a CSS library that's been around for ages (I think I used it when I was still in school). Historically you could download the "bootstrap CSS file", put it on your HTML page, and have access to their classes. The component library is simply a set of React components styled to look like Bootstrap.

Material UI looks like it's styled after common Android UI. I think we can probably go with that.

**Comment by gdirk07** [comment]
Going with Material UI
